databaseType = "MySql"
id = "c48fd9ed-2dbb-4a80-a31d-e04c40ad5292"
name = "skedjuli"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.local]
url = "jdbc:mysql://localhost:3306/skedjuli_db"
user = "root"
password = ""
