
spring.application.name=Skedjuli


spring.datasource.url=jdbc:postgresql://localhost:5432/skedjuli
spring.datasource.username=neznase //popunit
spring.datasource.password=neznase //popunit

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

# Server
server.port=8080

# Development
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true